### ISSUE TITLE
could I split timeline in different pages?

### ISSUE THREAD

**Issue by javimox** [OleVik/grav-plugin-timeline#10]
Hi,

first of all, many thanks for this great plugin. And here's my question:

- Do you think it would be possible to truncate timelines in different pages? E.g.: showing 5 or 10 events per page and then showing a "Go to next page" link, or something similar.

And here's my problem: when using youtube plugin and loading external content, if the timeline has too many events the page just hangs.

Example:
https://larosadecebrian.com/pasajes-de-la-historia-edad-moderna
https://larosadecebrian.com/pasajes-de-la-historia

P.S.: if no major plugin changes are necessary for this case and you can tell me where to start I can try to do something for myself and then PR it. Ty.

**Comment by OleVik** [comment]
I see the issue, there are three ways that this could be improved:

A) Lazy-load or otherwise offset resources until they come into view, like images, video, and the like.
B) Reduce the Timeline into smaller series, nesting it even further, for example a middle level for the 1400s, 1500s, etc, so that less Events are loaded at once.
C) I could implement pagination so that a set amount of Timelines and Events would be rendered for each Page.

What is your comfort-level with PHP and Twig? C) requires some API-changes to expose the `Content->buildTree`-method to Twig, but I think that's an enhancement I should do anyway for greater extensibility. Pagination itself should implement the interfaces from the [Pagination](https://github.com/getgrav/grav-plugin-pagination)-plugin, so that this plugin can operate more based on Collections.

**Comment by OleVik** [comment]
I have reviewed the code to see whether it can accommodate your use-case, or larger timelines generally. Because the plugin relies on a hierarchical set of Events within each Timeline, which can be nested, there is no uniform iteration through the items as a whole. Therefore it cannot be paginated; each nested Timeline is not counted in the same set as its siblings.

That said, a viable approach is to go further in what you appear to be already doing - my lack of Spanish notwithstanding: Keep the current periods you have, potentially splitting them further following B). This maintains the total hierarchy of pages as you have elsewhere. An alternative is to make them distinct, that is to reduce the nesting, which would achieve the same result.

The upcoming version 2.0.0 will implement more methods for Twig, following C), but they would not impact performance much. The suggestions in A) definitely would, however, and especially if a page loads many media-elements including images and video. This would make the biggest overall impact, as the rest of the page tends to be text and HTML.

**Comment by OleVik** [comment]
A new option in [v2.0.0-beta.1](https://github.com/OleVik/grav-plugin-timeline/releases/tag/v2.0.0-beta.1) lets you set a `limit` on how many levels to iterate downwards, which means you can perform the cutoff earlier without splitting Pages. This means lower levels will render complete Events, but not higher levels. You can experiment with this setting either in the plugin-configuration, or set in the FrontMatter of a `timeline.md`.
