### ISSUE TITLE
Date in frontmatter not showing in timeline.

### ISSUE THREAD

**Issue by cmadland** [OleVik/grav-plugin-timeline#8]
My timeline at grav.madland.ca/timeline has 3 events at the very bottom that are listed as 2019 contrary to the dates in the frontmatter.

![image](https://user-images.githubusercontent.com/12282929/70402319-d03cb280-19e7-11ea-845c-021acb4615a6.png)

<img width="547" alt="image" src="https://user-images.githubusercontent.com/12282929/70402338-e21e5580-19e7-11ea-9b45-aa4a9d46b067.png">

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/12282929/70402406-1a259880-19e8-11ea-84c5-1e8c3e0cd868.png">

I'm not sure where to look to resolve this.

**Comment by cmadland** [comment]
It seems to work properly when I have a full date in the date field.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/12282929/70725346-0eb8c280-1cb1-11ea-87a0-d8fc634d96ed.png">

But not with only the year.

**Comment by OleVik** [comment]
Yes, this is because the plugin needs a fully qualified date that PHP can parse, to allow a far range of dates. Normal Unix Epoch is insufficient in this regard, as dates should be available for thousands of years in the past and future. Even though natural datetimes like '1906' can be parsed fairly successfully, it fails when even a small amount of ambiguity is introduced.

Thus, even when you only want the year, it's best to flesh out the date to have something like:

```yaml
date: '01-01-1906'
date_format: 'Y'
```

The [examples in the skeleton](https://github.com/OleVik/grav-skeleton-timeline) includes the full ISO DateTime for this reason:

```yaml
date: '0321-07-03 00:00:28'
date_format: 'l jS of F Y'
```

I'll make a note to look for more pliable alternatives for date-parsing.
